name: Horion-Build

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: vcexpress project.sln /build
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: Horion
          path: x64\Debug\Horion.dll
