name: Horion-Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false
  release:
    types: [created]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: setup
      run: cmake .
    - name: Build
      run: make
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: Horion
          path: x64\Debug\Horion.dll
