name: Horion-1

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup 1
      run: FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
    - name: Setup 2
      run: SHELL ["cmd", "/S", "/C"]
    - name: Setup 3
      run: ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
    - name: Setup 4
      run: RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache ` --installPath C:\BuildTools ` --add Microsoft.VisualStudio.Workload.AzureBuildTools ` --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 ` --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 ` --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 ` --remove Microsoft.VisualStudio.Component.Windows81SDK ` || IF "%ERRORLEVEL%"=="3010" EXIT 0
    - name: Setup 5
      run: ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
    - name: Build
      run: msbuild Horion.sln
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: Horion
          path: x64\Debug\Horion.dll
