name: Horion-MSBuild

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2.3.2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: MSBuild
      run: msbuild Horion.vcxproj
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: Horion
          path: x64\Debug\Horion.dll
