name: Horion-Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false
  release:
    types: [created]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake .
    - name: Compile
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make
    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: Horion
          working-directory: ${{runner.workspace}}/build
          path: x64\Debug\Horion.dll
